use learning_sql;

/* 
 * If set A = {L M N O P} and set B = {P Q R S T}, what sets are generated by the following
 * operations?
 */


/** A union B */

SELECT elem FROM (
    SELECT "L" elem
    UNION 
    SELECT "M" elem 
    UNION
    SELECT "N" elem
    UNION
    SELECT "O" elem
    UNION
    SELECT "P" elem
) table1
UNION
SELECT elem from (
    SELECT "P" elem 
    UNION 
    SELECT "Q" elem 
    UNION
    SELECT "R" elem
    UNION
    SELECT "S" elem
    UNION
    SELECT "T" elem
) table2;